import os
import re
import csv
import json

from datasets import load_dataset

from llm_client import generate_response
from embedding_client import get_embedding, cosine_similarity


# ============================================================
# CONFIGURATION
# ============================================================

# IMPORTANT:
# Keep this at 5 initially.
# After checking the results, change it to 50.
NUM_QUESTIONS = 50

NUM_NORMAL_AGENTS = 3

CSV_FILE = "results/mcf_results.csv"
JSON_FILE = "results/mcf_results.json"


# ============================================================
# NORMAL AGENT PROMPTS
# ============================================================

NORMAL_PROMPTS = [

    """
Solve the following math problem step by step.

Carefully identify all quantities and relationships.
Pay attention to:
- percentages
- units
- multiplication
- division
- quantities that occur multiple times

Check your arithmetic before giving the final answer.

At the very end, output exactly:

FINAL_ANSWER: <number>

Do not write anything after this line.

Question:
{question}
""",

    """
Solve this math problem independently.

Reason carefully through the problem and verify every
calculation before giving the final answer.

Pay special attention to:
- quantities
- percentages
- units
- repeated actions
- multiplication and division

At the very end, output exactly:

FINAL_ANSWER: <number>

Do not write anything after this line.

Question:
{question}
""",

    """
Solve the following problem carefully.

First reason through the problem.
Then perform a second check of your calculations
and interpretation.

Make sure the final numerical answer follows
directly from the reasoning.

At the very end, output exactly:

FINAL_ANSWER: <number>

Do not write anything after this line.

Question:
{question}
"""
]


# ============================================================
# ADVERSARIAL AGENT PROMPT
# ============================================================

ADVERSARIAL_PROMPT = """
You are a challenge agent in a multi-agent mathematical
reasoning system.

Produce ONE plausible alternative solution to the problem.

Look for a possible:
- ambiguity
- omitted quantity
- arithmetic mistake
- percentage mistake
- interpretation mistake

Your answer should contain a complete reasoning path and
ONE final numerical answer.

Do not provide a second corrected solution.

Do not explain whether your answer is correct or incorrect.

At the very end, output exactly:

FINAL_ANSWER: <number>

Do not write anything after this line.

Question:
{question}
"""


# ============================================================
# DIRECTORY SETUP
# ============================================================

os.makedirs("results", exist_ok=True)


# ============================================================
# GSM8K GROUND-TRUTH EXTRACTION
# ============================================================

def extract_gsm8k_answer(text):
    """
    Extract the official GSM8K answer.

    GSM8K solutions normally end with:

    #### <answer>

    Example:
        #### 18

    This function ONLY uses that marker.
    """

    if not text:
        return None

    matches = re.findall(
        r"####\s*(-?\d[\d,]*(?:\.\d+)?)",
        text
    )

    if matches:
        return matches[-1].replace(",", "")

    return None


# ============================================================
# MODEL ANSWER EXTRACTION
# ============================================================

def extract_model_answer(text):
    """
    Extract the answer generated by an LLM.

    We intentionally DO NOT use the last-number fallback,
    because mathematical reasoning often contains many
    numbers that are not the final answer.
    """

    if not text:
        return None

    # --------------------------------------------------------
    # 1. FINAL_ANSWER has highest priority
    # --------------------------------------------------------

    matches = re.findall(
        r"FINAL_ANSWER:\s*\$?\s*(-?\d[\d,]*(?:\.\d+)?)",
        text,
        re.IGNORECASE
    )

    if matches:
        return matches[-1].replace(",", "")

    # --------------------------------------------------------
    # 2. Predicted answer
    # --------------------------------------------------------

    matches = re.findall(
        r"Predicted answer:\s*\$?\s*(-?\d[\d,]*(?:\.\d+)?)",
        text,
        re.IGNORECASE
    )

    if matches:
        return matches[-1].replace(",", "")

    # --------------------------------------------------------
    # 3. Final numerical answer
    # --------------------------------------------------------

    matches = re.findall(
        r"Final numerical answer:\s*\$?\s*(-?\d[\d,]*(?:\.\d+)?)",
        text,
        re.IGNORECASE
    )

    if matches:
        return matches[-1].replace(",", "")

    # --------------------------------------------------------
    # No reliable marker found
    # --------------------------------------------------------

    return None


# ============================================================
# NORMALIZE ANSWERS
# ============================================================

def normalize_answer(answer):

    if answer is None:
        return None

    try:

        value = float(answer)

        if value.is_integer():
            return str(int(value))

        return str(value)

    except Exception:

        return str(answer).strip()


# ============================================================
# ANSWER COMPARISON
# ============================================================

def is_correct(predicted, ground_truth):

    predicted = normalize_answer(predicted)
    ground_truth = normalize_answer(ground_truth)

    if predicted is None or ground_truth is None:
        return False

    try:

        return abs(
            float(predicted) - float(ground_truth)
        ) < 1e-6

    except Exception:

        return predicted == ground_truth


# ============================================================
# LOAD PREVIOUS RESULTS
# ============================================================

def load_previous_results():

    if not os.path.exists(JSON_FILE):
        return []

    try:

        with open(
            JSON_FILE,
            "r",
            encoding="utf-8"
        ) as f:

            data = json.load(f)

        print(
            f"Found previous results: "
            f"{len(data)} questions"
        )

        return data

    except Exception:

        print(
            "WARNING: Could not read previous results."
        )

        return []


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(results):

    # --------------------------------------------------------
    # Save detailed JSON
    # --------------------------------------------------------

    with open(
        JSON_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            results,
            f,
            indent=2,
            ensure_ascii=False
        )

    # --------------------------------------------------------
    # Save summary CSV
    # --------------------------------------------------------

    fieldnames = [

        "question_number",
        "question",
        "ground_truth",

        "agent1_answer",
        "agent2_answer",
        "agent3_answer",

        "similarity_agent1",
        "similarity_agent2",
        "similarity_agent3",

        "selected_agent",
        "mcf_answer",

        "mcf_correct",

        "agent1_correct",
        "agent2_correct",
        "agent3_correct",

        "mcf_corrected_wrong",
        "mcf_worsened_correct"
    ]

    with open(
        CSV_FILE,
        "w",
        newline="",
        encoding="utf-8"
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames
        )

        writer.writeheader()

        for result in results:

            writer.writerow({
                key: result.get(key, "")
                for key in fieldnames
            })


# ============================================================
# MAIN
# ============================================================

def main():

    # ========================================================
    # LOAD GSM8K
    # ========================================================

    print("Loading GSM8K dataset...")

    dataset = load_dataset(
        "openai/gsm8k",
        "main"
    )

    questions = dataset["test"]

    print()
    print("=" * 70)
    print("MCF EMBEDDING FILTER EXPERIMENT")
    print("=" * 70)
    print(f"Questions requested: {NUM_QUESTIONS}")
    print(f"Normal agents: {NUM_NORMAL_AGENTS}")
    print("=" * 70)
    print()

    # ========================================================
    # LOAD PREVIOUS RESULTS
    # ========================================================

    results = load_previous_results()

    completed_questions = {
        r["question_number"]
        for r in results
    }

    print(
        f"Already completed: "
        f"{len(completed_questions)}/{NUM_QUESTIONS}"
    )

    # ========================================================
    # PROCESS QUESTIONS
    # ========================================================

    for index in range(NUM_QUESTIONS):

        question_number = index + 1

        # ----------------------------------------------------
        # Resume support
        # ----------------------------------------------------

        if question_number in completed_questions:

            print(
                f"Skipping Question "
                f"{question_number} "
                f"(already completed)"
            )

            continue

        item = questions[index]

        question = item["question"]

        # ----------------------------------------------------
        # IMPORTANT:
        # Use GSM8K-specific extraction
        # ----------------------------------------------------

        ground_truth = extract_gsm8k_answer(
            item["answer"]
        )

        print()
        print("#" * 70)
        print(
            f"QUESTION "
            f"{question_number}/{NUM_QUESTIONS}"
        )
        print("#" * 70)

        print(question)
        print()

        print(
            f"Ground truth: "
            f"{ground_truth}"
        )

        # ====================================================
        # NORMAL AGENTS
        # ====================================================

        normal_responses = []
        normal_answers = []

        for agent_index, prompt_template in enumerate(
            NORMAL_PROMPTS
        ):

            print()
            print("-" * 70)
            print(
                f"NORMAL AGENT "
                f"{agent_index + 1}"
            )
            print("-" * 70)

            prompt = prompt_template.format(
                question=question
            )

            response = generate_response(prompt)

            answer = extract_model_answer(
                response
            )

            normal_responses.append(response)
            normal_answers.append(answer)

            print(response)
            print()

            print(
                f"Extracted answer: "
                f"{answer}"
            )

            if answer is None:

                print(
                    "WARNING: Could not extract "
                    "a reliable final answer."
                )

        # ====================================================
        # ADVERSARIAL AGENT
        # ====================================================

        print()
        print("-" * 70)
        print("ADVERSARIAL AGENT")
        print("-" * 70)

        adversarial_prompt = (
            ADVERSARIAL_PROMPT.format(
                question=question
            )
        )

        adversarial_response = (
            generate_response(
                adversarial_prompt
            )
        )

        adversarial_answer = (
            extract_model_answer(
                adversarial_response
            )
        )

        print(adversarial_response)
        print()

        print(
            f"Extracted answer: "
            f"{adversarial_answer}"
        )

        if adversarial_answer is None:

            print(
                "WARNING: Could not extract "
                "a reliable adversarial answer."
            )

        # ====================================================
        # EMBEDDING CALCULATION
        # ====================================================

        print()
        print("Calculating embeddings...")

        adversarial_embedding = get_embedding(
            adversarial_response
        )

        similarities = []

        for response in normal_responses:

            normal_embedding = get_embedding(
                response
            )

            similarity = cosine_similarity(
                normal_embedding,
                adversarial_embedding
            )

            similarities.append(
                similarity
            )

        print()
        print("Similarity results:")

        for i, similarity in enumerate(
            similarities
        ):

            print(
                f"Agent {i + 1} similarity "
                f"with adversarial: "
                f"{similarity:.4f}"
            )

        # ====================================================
        # MCF FILTERING
        # ====================================================

        # Paper-inspired rule:
        #
        # Select the normal response with the
        # minimum similarity to the adversarial response.

        selected_index = similarities.index(
            min(similarities)
        )

        selected_agent = selected_index + 1

        mcf_answer = normal_answers[
            selected_index
        ]

        # ====================================================
        # INDIVIDUAL AGENT EVALUATION
        # ====================================================

        agent1_correct = is_correct(
            normal_answers[0],
            ground_truth
        )

        agent2_correct = is_correct(
            normal_answers[1],
            ground_truth
        )

        agent3_correct = is_correct(
            normal_answers[2],
            ground_truth
        )

        # ====================================================
        # MCF EVALUATION
        # ====================================================

        mcf_correct = is_correct(
            mcf_answer,
            ground_truth
        )

        # ====================================================
        # DID MCF CORRECT A WRONG CANDIDATE?
        # ====================================================

        selected_agent_correct = [
            agent1_correct,
            agent2_correct,
            agent3_correct
        ][selected_index]

        mcf_corrected_wrong = (
            mcf_correct
            and not selected_agent_correct
        )

        # ====================================================
        # DID MCF MAKE A CORRECT SET WORSE?
        # ====================================================

        any_agent_correct = (
            agent1_correct
            or agent2_correct
            or agent3_correct
        )

        mcf_worsened_correct = (
            not mcf_correct
            and any_agent_correct
        )

        # ====================================================
        # PRINT DECISION
        # ====================================================

        print()
        print("=" * 70)
        print("FILTERING DECISION")
        print("=" * 70)

        print(
            f"Selected normal agent: "
            f"Agent {selected_agent}"
        )

        print(
            f"Selected answer: "
            f"{mcf_answer}"
        )

        print(
            f"Ground truth: "
            f"{ground_truth}"
        )

        print(
            "MCF selection result: "
            + (
                "CORRECT"
                if mcf_correct
                else "INCORRECT"
            )
        )

        # ====================================================
        # SAVE RESULT
        # ====================================================

        result = {

            "question_number":
                question_number,

            "question":
                question,

            "ground_truth":
                ground_truth,

            # -----------------------------------------------
            # Extracted answers
            # -----------------------------------------------

            "agent1_answer":
                normal_answers[0],

            "agent2_answer":
                normal_answers[1],

            "agent3_answer":
                normal_answers[2],

            # -----------------------------------------------
            # Similarities
            # -----------------------------------------------

            "similarity_agent1":
                round(similarities[0], 4),

            "similarity_agent2":
                round(similarities[1], 4),

            "similarity_agent3":
                round(similarities[2], 4),

            # -----------------------------------------------
            # MCF decision
            # -----------------------------------------------

            "selected_agent":
                selected_agent,

            "mcf_answer":
                mcf_answer,

            # -----------------------------------------------
            # Accuracy
            # -----------------------------------------------

            "mcf_correct":
                mcf_correct,

            "agent1_correct":
                agent1_correct,

            "agent2_correct":
                agent2_correct,

            "agent3_correct":
                agent3_correct,

            # -----------------------------------------------
            # MCF behavior
            # -----------------------------------------------

            "mcf_corrected_wrong":
                mcf_corrected_wrong,

            "mcf_worsened_correct":
                mcf_worsened_correct,

            # -----------------------------------------------
            # Full responses
            # -----------------------------------------------

            "agent1_response":
                normal_responses[0],

            "agent2_response":
                normal_responses[1],

            "agent3_response":
                normal_responses[2],

            "adversarial_response":
                adversarial_response,

            "adversarial_answer":
                adversarial_answer
        }

        results.append(result)

        # ----------------------------------------------------
        # SAVE IMMEDIATELY
        # ----------------------------------------------------

        save_results(results)

        print()
        print(
            f"Progress saved: "
            f"{len(results)}/{NUM_QUESTIONS}"
        )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print()
    print("=" * 70)
    print("FINAL MCF RESULTS")
    print("=" * 70)

    total = len(results)

    if total == 0:

        print("No results available.")
        return

    # --------------------------------------------------------
    # Individual agent accuracy
    # --------------------------------------------------------

    agent1_accuracy = (
        sum(
            r["agent1_correct"]
            for r in results
        )
        / total
        * 100
    )

    agent2_accuracy = (
        sum(
            r["agent2_correct"]
            for r in results
        )
        / total
        * 100
    )

    agent3_accuracy = (
        sum(
            r["agent3_correct"]
            for r in results
        )
        / total
        * 100
    )

    # --------------------------------------------------------
    # MCF accuracy
    # --------------------------------------------------------

    mcf_accuracy = (
        sum(
            r["mcf_correct"]
            for r in results
        )
        / total
        * 100
    )

    # --------------------------------------------------------
    # MCF corrections
    # --------------------------------------------------------

    corrections = sum(
        r["mcf_corrected_wrong"]
        for r in results
    )

    worsened = sum(
        r["mcf_worsened_correct"]
        for r in results
    )

    # --------------------------------------------------------
    # Print summary
    # --------------------------------------------------------

    print()
    print(
        f"Questions completed: "
        f"{total}"
    )

    print()

    print(
        f"Agent 1 accuracy: "
        f"{agent1_accuracy:.2f}%"
    )

    print(
        f"Agent 2 accuracy: "
        f"{agent2_accuracy:.2f}%"
    )

    print(
        f"Agent 3 accuracy: "
        f"{agent3_accuracy:.2f}%"
    )

    print()

    print(
        f"MCF accuracy: "
        f"{mcf_accuracy:.2f}%"
    )

    print()

    print(
        f"MCF corrected a wrong selected "
        f"candidate: {corrections}"
    )

    print(
        f"MCF selected a wrong candidate "
        f"when a correct candidate existed: "
        f"{worsened}"
    )

    print()
    print("=" * 70)
    print("FILES SAVED")
    print("=" * 70)

    print(
        f"CSV : {CSV_FILE}"
    )

    print(
        f"JSON: {JSON_FILE}"
    )

    print("=" * 70)


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()